In [1]:
import pandas as pd
import plotly.plotly as py
import plotly.figure_factory as ff
import pandas as pd
import numpy as np
from collections import Counter


print('Loaded Libraries')

Loaded Libraries

In [20]:
df = pd.read_csv("globalterrorismdb_0617dist.csv", encoding = "ISO-8859-1")
print('Original Data Shape:' + str(df.shape))
df.head()

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning:

Columns (9,29,31,51,59,60,61,74,77,88,90,92,94,112,113,119) have mixed types. Specify dtype option on import or set low_memory=False.

Original Data Shape:(170350, 131)

,country_txt,country,region_txt,region,city,provstate,iyear,imonth,iday,approxdate,...,hostkidoutcome_txt,nreleased,scite1,scite2,scite3,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,Dominican Republic,58,Central America & Caribbean,2,Santo Domingo,NaN,1970,7,2,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,0,0,NaN
1,Mexico,130,North America,1,Mexico city,NaN,1970,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,0,1,1,1,NaN
2,Philippines,160,Southeast Asia,5,Unknown,Tarlac,1970,1,0,NaN,...,NaN,NaN,NaN,NaN,NaN,-9,-9,1,1,NaN
3,Greece,78,Western Europe,8,Athens,Attica,1970,1,0,NaN,...,NaN,NaN,NaN,NaN,NaN,-9,-9,1,1,NaN
4,Japan,101,East Asia,4,Fukouka,NaN,1970,1,0,NaN,...,NaN,NaN,NaN,NaN,NaN,-9,-9,1,1,NaN

In [21]:
print(df.info())
print('-------------')
print(list(df.columns))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170350 entries, 0 to 170349
Columns: 131 entries, country_txt to related
dtypes: float64(53), int64(23), object(55)
memory usage: 170.3+ MB
None
-------------
['country_txt', 'country', 'region_txt', 'region', 'city', 'provstate', 'iyear', 'imonth', 'iday', 'approxdate', 'extended', 'latitude', 'longitude', 'specificity', 'vicinity', 'location', 'summary', 'crit1', 'crit2', 'crit3', 'doubtterr', 'alternative', 'alternative_txt', 'multiple', 'success', 'suicide', 'attacktype1', 'attacktype1_txt', 'attacktype2', 'attacktype2_txt', 'attacktype3', 'attacktype3_txt', 'targtype1', 'targtype1_txt', 'targsubtype1', 'targsubtype1_txt', 'corp1', 'target1', 'natlty1', 'natlty1_txt', 'targtype2', 'targtype2_txt', 'targsubtype2', 'targsubtype2_txt', 'corp2', 'target2', 'natlty2', 'natlty2_txt', 'targtype3', 'targtype3_txt', 'targsubtype3', 'targsubtype3_txt', 'corp3', 'target3', 'natlty3', 'natlty3_txt', 'gname', 'gsubname', 'gname2', 'gsubname2', 'gname3', 'gsubname3', 'motive', 'guncertain1', 'guncertain2', 'guncertain3', 'individual', 'nperps', 'nperpcap', 'claimed', 'claimmode', 'claimmode_txt', 'claim2', 'claimmode2', 'claimmode2_txt', 'claim3', 'claimmode3', 'claimmode3_txt', 'compclaim', 'weaptype1', 'weaptype1_txt', 'weapsubtype1', 'weapsubtype1_txt', 'weaptype2', 'weaptype2_txt', 'weapsubtype2', 'weapsubtype2_txt', 'weaptype3', 'weaptype3_txt', 'weapsubtype3', 'weapsubtype3_txt', 'weaptype4', 'weaptype4_txt', 'weapsubtype4', 'weapsubtype4_txt', 'weapdetail', 'nkill', 'nkillus', 'nkillter', 'nwound', 'nwoundus', 'nwoundte', 'property', 'propextent', 'propextent_txt', 'propvalue', 'propcomment', 'ishostkid', 'nhostkid', 'nhostkidus', 'nhours', 'ndays', 'divert', 'kidhijcountry', 'ransom', 'ransomamt', 'ransomamtus', 'ransompaid', 'ransompaidus', 'ransomnote', 'hostkidoutcome', 'hostkidoutcome_txt', 'nreleased', 'scite1', 'scite2', 'scite3', 'INT_LOG', 'INT_IDEO', 'INT_MISC', 'INT_ANY', 'related']

### Select Column of Interests. Namely:
- Year
- Country
- Region
- Criteria
    - 1. Political, Economic, Religious, or Social Goal
    - 2. Intent to Coerce, Intimidate, or publicize to larger audience
    - 3. outside international humanitarian laws
- Type of attack
    1. Assassination 
    2. Hijacking
    3. Kidnapping
    4. Barricade Incident Bombing/Explosion
    5. Armed Assault
    6. Unarmed Assault Facility/Infrastructure Attack
    7. Unknown (should we remove all unknowns?)
    
- suicide 
    0- no, 1 yes
- Sucessful attack
    - 0 fail
    - 1 success
- Weapon information (type)
    1. Biological
    2. Chemical
    3. Radiological
    4. Nuclear
    5. Firearms
    6. explosive/bombs
    7. Fake weapons
    8. Incendiary
    9. Melee
    10. Vehicle
    11. Sabatoage 
    12. Other
    13. Unknown
- Target/Victim Info
    1. Business
    2. Government (general)
    3. Police
    4. Military
    5. Abortion related
    6. airports/aircraft
    7. Govenerment (diplomatic)
    8. Educational institution
    9. food/water supply
    10. jounrlists/media
    11. Maritime
    12. Ngo
    13. Other
    14. Private citizens/property
    15. Religious
    16. Telecomm
    17. terrorists/non state militias
    18. Tourists
    19. Transportaion
    20. Unkown 
    21. Utilties 
    22. Violent polical parties

- Casualities
     - nkill- total number of kills,
     - nwound- total number of wounded
     - property damage- 0 no, 1 yes
     - property extent of damage
         1. Catastrophic (likely > 1 billion USD)
         2. Major (likely > 1 million but < 1 billion USD)
         3. Minor (likely < 1 million USD)
         4. Unknown
     - propvalue- value of property destroyed

In [3]:
cols_of_interest = ["iyear", 
                    'success',
                    'suicide',
                    'region_txt', 
                     'attacktype1_txt',
                     'targtype1_txt',
                     'weaptype1_txt',
                     'propextent_txt',
                     'nkill',
                     'nperps',
                     'nwound',
                     'propvalue']

new_df = df[cols_of_interest]

In [26]:
print("Before Dropping NA Values: " + str(new_df.shape))

# Drop NA Values
newer_df = new_df.dropna()
print("After Dropping NA Values: " + str(newer_df.shape))
newer_df.head()

Before Dropping NA Values: (170350, 12)
After Dropping NA Values: (23919, 12)

,iyear,success,suicide,region_txt,attacktype1_txt,targtype1_txt,weaptype1_txt,propextent_txt,nkill,nperps,nwound,propvalue
7,1970,1,0,North America,Bombing/Explosion,Utilities,Explosives/Bombs/Dynamite,Minor (likely < $1 million),0.0,-99.0,0.0,22500.0
8,1970,1,0,North America,Facility/Infrastructure Attack,Military,Incendiary,Minor (likely < $1 million),0.0,1.0,0.0,60000.0
11,1970,1,0,North America,Facility/Infrastructure Attack,Military,Incendiary,Minor (likely < $1 million),0.0,-99.0,0.0,305.0
14,1970,1,0,North America,Facility/Infrastructure Attack,Business,Incendiary,Major (likely > $1 million but < $1 billion),0.0,-99.0,0.0,2000000.0
19,1970,1,0,North America,Facility/Infrastructure Attack,Business,Incendiary,Minor (likely < $1 million),0.0,-99.0,0.0,17000.0

### Convert Categorical Data to Dummy Variables

In [29]:
region_dummy = pd.get_dummies(newer_df["region_txt"])
attacktype1_dummy  = pd.get_dummies(newer_df["attacktype1_txt"])
targtype_txt_dummy  = pd.get_dummies(newer_df["targtype1_txt"])
prop_extent_txt_dummy  = pd.get_dummies(newer_df["propextent_txt"])
weaptype_txt_dummy  = pd.get_dummies(newer_df["weaptype1_txt"])
# weapsubtype_txt_dummy  = pd.get_dummies(newer_df["weapsubtype1_txt"])

In [30]:
numerical_cols = ["iyear", 'success', 'suicide', 'nkill', 'nwound', 'propvalue', 'nperps']
final_df = pd.concat([newer_df, region_dummy, attacktype1_dummy, targtype_txt_dummy, prop_extent_txt_dummy, weaptype_txt_dummy], axis=1)
final_df.head()

,iyear,success,suicide,region_txt,attacktype1_txt,targtype1_txt,weaptype1_txt,propextent_txt,nkill,nperps,...,Unknown,Chemical,Explosives/Bombs/Dynamite,Firearms,Incendiary,Melee,Other,Sabotage Equipment,Unknown,"Vehicle (not to include vehicle-borne explosives, i.e., car or truck bombs)"
7,1970,1,0,North America,Bombing/Explosion,Utilities,Explosives/Bombs/Dynamite,Minor (likely < $1 million),0.0,-99.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,1970,1,0,North America,Facility/Infrastructure Attack,Military,Incendiary,Minor (likely < $1 million),0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
11,1970,1,0,North America,Facility/Infrastructure Attack,Military,Incendiary,Minor (likely < $1 million),0.0,-99.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
14,1970,1,0,North America,Facility/Infrastructure Attack,Business,Incendiary,Major (likely > $1 million but < $1 billion),0.0,-99.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
19,1970,1,0,North America,Facility/Infrastructure Attack,Business,Incendiary,Minor (likely < $1 million),0.0,-99.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [35]:
# Remove Values Where 'nperps' equals -99 or Unknown
final_df = final_df[df["nperps"] != -99]

final_df.shape

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

(4730, 68)

In [9]:
# Save Cleaned Data
final_df.to_csv("cleaned_data.csv", encoding='utf-8')